name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Build
        run: go build

  verify_tailwind:
    name: "Verify Tailwind"
    env:
      TAILWIND_VERSION: v4.1.5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tailwind
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${{ env.TAILWIND_VERSION }}/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          # Move tailwind to $PATH
          mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

      - name: Verify Tailwind
        run: |
          tailwindcss -i web/input.css -o web/output.css
          DIFF=$(git diff)
          if [ -n "$DIFF" ]; then
            echo "::error file=web/output.css,line=1,col=1,title=STALE-TAILWIND::Tailwind generated CSS was out of date! Please regenerate it."
            echo "Diff:"
            echo ""
            git diff
            exit 1
          fi

  verify_templ:
    name: "Verify Templ"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: Verify Templ
        run: |
          go tool templ generate
          DIFF=$(git diff)
          if [ -n "$DIFF" ]; then
            echo "::error title=STALE-TEMPL::Templ generation was out of date! Please regenerate it."
            echo "Diff:"
            echo ""
            git diff
            exit 1
          fi
