name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  CI:
    env:
      TAILWIND_VERSION: v4.1.5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tailwind
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/${{ env.TAILWIND_VERSION }}/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          # Move tailwind to $PATH
          mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

      - name: Generate Tailwind
        run: tailwindcss -i web/input.css -o web/output.css

      - name: Verify Tailwind
        run: |
          DIFF=$(git diff)
          if [ -n "$DIFF" ]; then
            echo "::error file=web/output.css,line=1,col=1,title=STALE-TAILWIND::Tailwind generated CSS was out of date! Please regenerate it."
            echo "Diff:"
            echo ""
            git diff
            exit 1
          fi
